name: test

on:
  # pull_request:
  #   branches:
  #     - '*'
  workflow_dispatch:

jobs:
  hello:
    name: hello
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: echo "Hello world"